# -*- coding: utf-8 -*-
#
# Configuration file for the Sphinx documentation builder.
#
# This file does only contain a selection of the most common options. For a
# full list see the documentation:
# http://www.sphinx-doc.org/en/master/config

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import os
import sys
import importlib.util
import re

docs_dir = os.path.abspath(os.path.dirname(__file__))
src_dir = os.path.abspath(os.path.join(docs_dir, ".."))
sys.path.insert(0, src_dir)
sys.path.insert(0, src_dir + "/src")


# -- Project information -----------------------------------------------------

project = "PySME"
copyright = "2025, Jeff Valenti, Nikolai Piskunov, Mingjie Jian, Ansgar Wehrhahn"
author = "Jeff Valenti, Nikolai Piskunov, Mingjie Jian, Ansgar Wehrhahn"

def _resolve_release():
    """Resolve docs version from versioneer without importing pysme package.

    Importing ``pysme`` would trigger heavy runtime side effects in ``__init__``.
    We therefore load ``src/pysme/_version.py`` directly.
    """
    version_file = os.path.join(src_dir, "src", "pysme", "_version.py")
    try:
        spec = importlib.util.spec_from_file_location("pysme_version", version_file)
        if spec is None or spec.loader is None:
            raise RuntimeError(f"Could not load version spec from: {version_file}")
        module = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(module)
        return module.get_versions().get("version", "unknown")
    except Exception:
        # Fallbacks keep docs buildable even without full VCS metadata.
        return (
            os.environ.get("READTHEDOCS_GIT_IDENTIFIER")
            or os.environ.get("READTHEDOCS_VERSION")
            or "unknown"
        )


def _read_pyproject_version():
    """Read project version from pyproject.toml without extra dependencies."""
    pyproject = os.path.join(src_dir, "pyproject.toml")
    try:
        with open(pyproject, "r", encoding="utf-8") as f:
            content = f.read()
        match = re.search(r'^\s*version\s*=\s*"([^"]+)"\s*$', content, re.MULTILINE)
        if match:
            return match.group(1)
    except Exception:
        pass
    return None


# The full version, including local build metadata (e.g. +g<sha>.dirty)
release = _resolve_release()
if release:
    release_lower = release.lower()
    if release_lower.startswith("0+untagged") or release_lower.startswith("0+unknown"):
        pyproject_version = _read_pyproject_version()
        if pyproject_version:
            release = pyproject_version
# The short X.Y version shown by Sphinx.
short_release = release.split("+")[0]
version_parts = short_release.split(".")
version = ".".join(version_parts[:2]) if len(version_parts) >= 2 else short_release


# -- General configuration ---------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'myst_parser',
    "sphinx.ext.autodoc",
    "sphinx.ext.todo",
    "sphinx.ext.coverage",
    "sphinx.ext.mathjax",
    "sphinx.ext.viewcode",
    "sphinx.ext.githubpages",
    "sphinx.ext.napoleon",
    "sphinx_math_dollar"
]

myst_enable_extensions =[
    'strikethrough',
    'fieldlist'
]

autodoc_member_order = "groupwise"

# Add any paths that contain templates here, relative to this directory.
templates_path = ["_templates"]

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
# source_suffix = ".rst"
source_suffix = {
    '.rst': 'restructuredtext',
    '.txt': 'markdown',
    '.md': 'markdown',
}       

# The master toctree document.
master_doc = "index"

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = "en"

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path .
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store", "**.ipynb_checkpoints"]

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = "sphinx"


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = "sphinx_book_theme"

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
# html_theme_options = {}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ["_static"]

html_logo = "_static/pysme_logo-light.png"   # 路径相对 docs/
html_theme_options = {
   "logo": {
      "image_light": "_static/pysme_logo-light.png",
      "image_dark": "_static/pysme_logo-dark.png",
   }
}
html_css_files = ["custom.css"]

# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
#
# The default sidebars (for documents that don't match any pattern) are
# defined by theme itself.  Builtin themes are using these templates by
# default: ``['localtoc.html', 'relations.html', 'sourcelink.html',
# 'searchbox.html']``.
#
# html_sidebars = {}


# -- Options for HTMLHelp output ---------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = "SMEdoc"


# -- Options for LaTeX output ------------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',
    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',
    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',
    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (
        master_doc,
        "SME.tex",
        "SME Documentation",
        "Jeff Valenti, Nikolai Piskunov, Ansgar Wehrhahn, Mingjie Jian",
        "manual",
    )
]


# -- Options for manual page output ------------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [(master_doc, "sme", "SME Documentation", [author], 1)]


# -- Options for Texinfo output ----------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (
        master_doc,
        "SME",
        "SME Documentation",
        author,
        "SME",
        "One line description of project.",
        "Miscellaneous",
    )
]


# -- Extension configuration -------------------------------------------------

# -- Options for todo extension ----------------------------------------------

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = True
